(define (domain sokoban)
 (:requirements :strips :typing)
 (:types player box position)
 (:predicates
  (player-at ?p - player ?pos - position)
  (box-at ?b - box ?pos - position)
  (goal ?b - box ?pos - position)
  (empty ?pos - position)
  (adj-up ?f ?t - position)
  (adj-down ?f ?t - position)
  (adj-left ?f ?t - position)
  (adj-right ?f ?t - position)
 )
 (:action move
  :parameters (?p - player ?f ?t - position)
  :precondition (and (player-at ?p ?f) (empty ?t)
    (or (adj-up ?f ?t)(adj-down ?f ?t)(adj-left ?f ?t)(adj-right ?f ?t)))
  :effect (and (not (player-at ?p ?f)) (player-at ?p ?t) (empty ?f) (not (empty ?t)))
 )
 (:action push-up
  :parameters (?p - player ?b - box ?f ?t ?n - position)
  :precondition (and (player-at ?p ?f)(box-at ?b ?t)(adj-up ?f ?t)(adj-up ?t ?n)(empty ?n))
  :effect (and (player-at ?p ?t)(not (player-at ?p ?f))(box-at ?b ?n)(not (box-at ?b ?t))(empty ?f)(not (empty ?n)))
 )
 (:action push-down
  :parameters (?p - player ?b - box ?f ?t ?n - position)
  :precondition (and (player-at ?p ?f)(box-at ?b ?t)(adj-down ?f ?t)(adj-down ?t ?n)(empty ?n))
  :effect (and (player-at ?p ?t)(not (player-at ?p ?f))(box-at ?b ?n)(not (box-at ?b ?t))(empty ?f)(not (empty ?n)))
 )
 (:action push-left
  :parameters (?p - player ?b - box ?f ?t ?n - position)
  :precondition (and (player-at ?p ?f)(box-at ?b ?t)(adj-left ?f ?t)(adj-left ?t ?n)(empty ?n))
  :effect (and (player-at ?p ?t)(not (player-at ?p ?f))(box-at ?b ?n)(not (box-at ?b ?t))(empty ?f)(not (empty ?n)))
 )
 (:action push-right
  :parameters (?p - player ?b - box ?f ?t ?n - position)
  :precondition (and (player-at ?p ?f)(box-at ?b ?t)(adj-right ?f ?t)(adj-right ?t ?n)(empty ?n))
  :effect (and (player-at ?p ?t)(not (player-at ?p ?f))(box-at ?b ?n)(not (box-at ?b ?t))(empty ?f)(not (empty ?n)))
 )
)